# Generated by Django 4.1.1 on 2022-11-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionusuario',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
