# Generated by Django 4.1.1 on 2022-11-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_extensionusuario_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionusuario',
            name='website',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
