# Generated by Django 4.1.1 on 2022-10-16 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='crear_usuarios',
            new_name='Crear',
        ),
        migrations.RenameModel(
            old_name='inicio_sesion',
            new_name='Inicar',
        ),
    ]
