# Generated by Django 4.1.2 on 2022-10-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_rename_crear_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apellido',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
