# Generated by Django 4.1.1 on 2022-11-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_alter_user_apellido_alter_user_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inicar',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='apellido',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
