# Generated by Django 4.1.1 on 2022-11-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_delete_inicar_rename_apellido_user_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
